name: Avisos Secundario

on:
  schedule:
    - cron: "0 23 * * *"   # todos los días 20:00 (UTC-3) = 23:00 UTC
  workflow_dispatch: {}    # para ejecutarlo a mano desde ActionsS

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Instala deps del SO + navegadores Playwright
      - name: Install Playwright deps
        uses: microsoft/playwright-github-action@v1
        with:
          version: "1.48.0"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run scraper
        env:
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
          URL_TABLA: ${{ secrets.URL_TABLA }}

        run: |
          python test_mail.py --url "$URL_TABLA" --chromium
